Repository sonic-net/sonic-py-swsssdk, pull requests merged in 2022-03, with the labels that each got.

#118 define index for VoQ recirc port
  src/swsssdk/port_util.py
Labels: Chassis, Request for 202106 branch, Request for 202111 Branch

#119 [build] pin pytest-azurepipelines version
  azure-pipelines.yml
Labels: ci

#117 [port_util] Fix issue: port_util.get_vlan_interface_oid_map should not raise exception when DB has not RIF data
  src/swsssdk/port_util.py
  test/test_port_util.py
Labels: Request for 202111 Branch
